//---------------------------------------------------------------------------------------------------------------------
// 13.)Find all the listings with name, address, reviewer_name, and review_scores_rating in the listingsAndReviews
//collection that have a "hot tub" amenity and are located in the United States.
//---------------------------------------------------------------------------------------------------------------------

// INPUT:
db.denem4.find(
    {
        "address.country": "United States",
        "amenities": "Hot tub",
        "name": { "$exists": true },
        "address": { "$exists": true },
        "reviews.reviewer_name": { "$exists": true },
        "review_scores.review_scores_rating": { "$exists": true }
    },
    {
        "name": 1,
        "address": 1,
        "reviews.reviewer_name": 1,
        "review_scores.review_scores_rating": 1,
        "amenities": 1
    }
).limit(2).pretty()


// OUTPUT:
[
  {
    _id: '1001265',
    name: 'Ocean View Waikiki Marina w/prkg',
    amenities: [
      'TV',
      'Cable TV',
      'Wifi',
      'Air conditioning',
      'Pool',
      'Kitchen',
      'Free parking on premises',
      'Elevator',
      'Hot tub',
      'Washer',
      'Dryer',
      'Essentials',
      'Shampoo',
      'Hangers',
      'Hair dryer',
      'Iron',
      'Laptop friendly workspace',
      'Self check-in',
      'Lockbox',
      'Hot water',
      'Bed linens',
      'Extra pillows and blankets',
      'Ethernet connection',
      'Microwave',
      'Coffee maker',
      'Refrigerator',
      'Dishes and silverware',
      'Cooking basics',
      'Stove',
      'BBQ grill',
      'Garden or backyard',
      'Well-lit path to entrance',
      'Disabled parking spot',
      'Step-free access',
      'Wide clearance to bed',
      'Step-free access'
    ],
    address: {
      street: 'Honolulu, HI, United States',
      suburb: 'Oʻahu',
      government_area: 'Primary Urban Center',
      market: 'Oahu',
      country: 'United States',
      country_code: 'US',
      location: {
        type: 'Point',
        coordinates: [
          { '$numberDouble': '-157.83919' },
          { '$numberDouble': '21.28634' }
        ],
        is_location_exact: true
      }
    },
    review_scores: { review_scores_rating: 84 },
    reviews: [
      { reviewer_name: 'Jacqui' },
      { reviewer_name: 'Khoren' },
      { reviewer_name: 'Nick' },
      { reviewer_name: 'Jean' },
      { reviewer_name: 'Dhaval' },
      { reviewer_name: 'Carol E' },
      { reviewer_name: 'Sophie & Lo' },
      { reviewer_name: 'Tj' },
      { reviewer_name: 'Rose' },
      { reviewer_name: 'Susan' },
      { reviewer_name: 'Tami' },
      { reviewer_name: 'Christopher' },
      { reviewer_name: 'Robert' },
      { reviewer_name: 'Christian' },
      { reviewer_name: 'Jessica And Ryan' },
      { reviewer_name: 'Shawn' },
      { reviewer_name: 'Eric' },
      { reviewer_name: 'Sebastiana' },
      { reviewer_name: 'Jenell' },
      { reviewer_name: 'Jason' },
      { reviewer_name: 'Katharine' },
      { reviewer_name: 'Mike' },
      { reviewer_name: 'Kai' },
      { reviewer_name: 'Wendy' },
      { reviewer_name: 'Silke' },
      { reviewer_name: 'James' },
      { reviewer_name: 'Matthew' },
      { reviewer_name: 'Carolyn' },
      { reviewer_name: 'Gina' },
      { reviewer_name: 'Dan' },
      { reviewer_name: 'Julia' },
      { reviewer_name: 'Warren' },
      { reviewer_name: 'Paula' },
      { reviewer_name: 'Herve' },
      { reviewer_name: 'Debbie' },
      { reviewer_name: 'Lawron' },
      { reviewer_name: 'Tuguy' },
      { reviewer_name: 'Matthew' },
      { reviewer_name: 'Alizée' },
      { reviewer_name: 'Garret' },
      { reviewer_name: 'Alyssa' },
      { reviewer_name: 'None' },
      { reviewer_name: 'Helene' },
      { reviewer_name: 'Pong' },
      { reviewer_name: 'Ross' },
      { reviewer_name: 'Mike' },
      { reviewer_name: 'Liza' },
      { reviewer_name: 'Sara' },
      { reviewer_name: 'James' },
      { reviewer_name: 'Susan' },
      { reviewer_name: 'Larry' },
      { reviewer_name: 'Daniel' },
      { reviewer_name: 'Connie' },
      { reviewer_name: 'Laura' },
      { reviewer_name: 'Todd' },
      { reviewer_name: 'Cerys' },
      { reviewer_name: 'Stephanie' },
      { reviewer_name: 'Mark' },
      { reviewer_name: 'Annie' },
      { reviewer_name: 'Sean' },
      { reviewer_name: 'Gilda' },
      { reviewer_name: 'Edward & Yang Qian' },
      { reviewer_name: 'Natalie Jane' },
      { reviewer_name: 'Laurie' },
      { reviewer_name: 'Park' },
      { reviewer_name: 'Colin' },
      { reviewer_name: 'Will' },
      { reviewer_name: 'Gabriela' },
      { reviewer_name: 'Courtney' },
      { reviewer_name: 'Ian' },
      { reviewer_name: 'Alex' },
      { reviewer_name: 'Sigrid' },
      { reviewer_name: 'Xing' },
      { reviewer_name: 'Rafael' },
      { reviewer_name: 'Rao' },
      { reviewer_name: '(Email hidden by Airbnb)' },
      { reviewer_name: 'Karn' },
      { reviewer_name: 'Eiman' },
      { reviewer_name: 'Hwisun' },
      { reviewer_name: 'Todd' },
      { reviewer_name: 'Larry V' },
      { reviewer_name: 'Donna' },
      { reviewer_name: 'Chang Kong' },
      { reviewer_name: 'Amanda' },
      { reviewer_name: 'Jeff' },
      { reviewer_name: 'Galina' },
      { reviewer_name: 'Rhonda' },
      { reviewer_name: 'James' },
      { reviewer_name: 'Lianne' },
      { reviewer_name: 'Eugene' },
      { reviewer_name: 'Shahin' },
      { reviewer_name: 'Chaundra' },
      { reviewer_name: 'Martina' },
      { reviewer_name: 'Robert' },
      { reviewer_name: 'Rhonda' },
      { reviewer_name: 'Wendi' }
    ]
  },
  {
    _id: '10166986',
    name: 'Resort-like living in Williamsburg',
    amenities: [
      'TV',
      'Internet',
      'Wifi',
      'Air conditioning',
      'Wheelchair accessible',
      'Pool',
      'Kitchen',
      'Doorman',
      'Gym',
      'Elevator',
      'Hot tub',
      'Buzzer/wireless intercom',
      'Heating',
      'Family/kid friendly',
      'Washer',
      'Dryer',
      'Smoke detector',
      'Essentials',
      '24-hour check-in',
      'Hangers',
      'Iron'
    ],
    address: {
      street: 'Brooklyn, NY, United States',
      suburb: 'Williamsburg',
      government_area: 'Williamsburg',
      market: 'New York',
      country: 'United States',
      country_code: 'US',
      location: {
        type: 'Point',
        coordinates: [
          { '$numberDouble': '-73.93869' },
          { '$numberDouble': '40.71552' }
        ],
        is_location_exact: true
      }
    },
    review_scores: { review_scores_rating: 100 },
    reviews: [ { reviewer_name: 'David' } ]
  }
]